name: flutter_rick
description: "A Simple Rick and Morty APP for iOS and Android, build with Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #State management
  flutter_bloc: ^8.1.2

  #Simplify Equality Comparisons
  equatable: ^2.0.5

  #DI
  get_it: ^7.6.7

  #Retrofit
  retrofit: '>=4.0.0 <5.0.0'
  logger: any  #for logging purpose
  json_annotation: ^4.8.1
  dio: ^5.4.0

  #Cached Image
  cached_network_image: ^3.3.1

  #Database SQLite
  floor: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2
  floor_generator: ^1.4.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_rick_app.png"

flutter:
  uses-material-design: true